version: "2"
run:
  timeout: 2m
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errchkjson
    - errorlint
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 40
    gosec:
      excludes:
        - G204
    lll:
      line-length: 140
      tab-width: 1
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 20
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
  exclusions:
    rules:
      - text: "shadow: declaration of .err. shadows declaration"
        path: (.+)\.go$
      - text: "SA1019"
        path: (.+)\.go$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - http-everything/httpe
